/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-11-24 05:51:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Admin_005fpanel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <title>Admin panel</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom fonts for this template-->\r\n");
      out.write("  <link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template-->\r\n");
      out.write("  <link href=\"css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Wrapper -->\r\n");
      out.write("  <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Sidebar - Brand -->\r\n");
      out.write("      <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"Admin_panel.jsp\">\r\n");
      out.write("        <div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("          <i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sidebar-brand-text mx-3\">Admin</div>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Divider -->\r\n");
      out.write("      <hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Nav Item - Dashboard -->\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"Admin_panel.jsp\">\r\n");
      out.write("          <i class=\"fas fa-fw fa-tachometer-alt\"></i>\r\n");
      out.write("          <span>Admin</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      <!-- Divider -->\r\n");
      out.write("      <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Heading -->\r\n");
      out.write("      <div class=\"sidebar-heading\">\r\n");
      out.write("        Details\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("  <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"JS_viewpro.jsp\">\r\n");
      out.write("      <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("          <span>Candidate Details</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("  <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"Accepthr.jsp\">\r\n");
      out.write("      <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("          <span>HR Requests</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("  <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"Profile_from_robot.jsp\">\r\n");
      out.write(" <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("          <span>Robot Updates</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write(" <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"Index.html\">\r\n");
      out.write(" <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("          <span>Logout</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("       \r\n");
      out.write(" \r\n");
      out.write("      <!-- Divider -->\r\n");
      out.write("      <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("      <div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("        <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("    <!-- End of Sidebar -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Content Wrapper -->\r\n");
      out.write("    <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Main Content -->\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Topbar -->\r\n");
      out.write("        <nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("          <button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("            <i class=\"fa fa-bars\"></i>\r\n");
      out.write("          </button>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("          <!-- Topbar Navbar -->\r\n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - User Information -->\r\n");
      out.write("           <li class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">Admin\t\t</span>\r\n");
      out.write("                <img class=\"img-profile rounded-circle\" src=\"img/admin.png\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <!-- Dropdown - User Information -->\r\n");
      out.write("              <div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"userDropdown\">\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"Index.html\" data-toggle=\"modal\" data-target=\"#logoutModal\">\r\n");
      out.write("                  <i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("                  Logout\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- End of Topbar -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Begin Page Content -->\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Page Heading -->\r\n");
      out.write("          <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\r\n");
      out.write("           <marquee> <h1 class=\"h3 mb-0 text-gray-800\"> A Resume Evaluation System Based on Text Mining</h1></marquee>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Content Row -->\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-primary shadow h-100 py-2\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                      <a class=\"text-xs font-weight-bold text-primary text-uppercase mb-1\" style=\"font-size:20px;\" href=\"JS_viewpro.jsp\">Candidate Details</a></div>\r\n");
      out.write("                      <div class=\"h5 mb-0 font-weight-bold text-gray-800\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                     <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\r\n");
      out.write("                    <!--   <i class=\"fas fa-calendar fa-2x text-gray-300\"></i> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-success shadow h-100 py-2\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                      <a href=\"Accepthr.jsp\" class=\"text-xs font-weight-bold text-success text-uppercase mb-1\" style=\"font-size:20px;\" >HR Requests</a></div>\r\n");
      out.write("                      <div class=\"h5 mb-0 font-weight-bold text-gray-800\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                       <i class=\"fas fa-calendar fa-2x text-gray-300\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-info shadow h-100 py-2\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                      <a style=\"font-size:20px;\" class=\"text-xs font-weight-bold text-info text-uppercase mb-1\" href=\"Profile_from_robot.jsp\" >Robot Updates</a></div>\r\n");
      out.write("                      <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                        <div class=\"col-auto\">\r\n");
      out.write("                          <div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       \r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                      <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Pending Requests Card Example -->\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("          <img src=\"img/back1.jpg\">\r\n");
      out.write("          <!-- Content Row -->\r\n");
      out.write("  <!-- Bootstrap core JavaScript-->\r\n");
      out.write("  <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Core plugin JavaScript-->\r\n");
      out.write("  <script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom scripts for all pages-->\r\n");
      out.write("  <script src=\"js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page level plugins -->\r\n");
      out.write("  <script src=\"vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page level custom scripts -->\r\n");
      out.write("  <script src=\"js/demo/chart-area-demo.js\"></script>\r\n");
      out.write("  <script src=\"js/demo/chart-pie-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
