/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-11-24 06:16:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.nio.file.Files;
import java.nio.file.Path;
import org.apache.log4j.Logger;
import org.apache.log4j.MDC;
import java.io.*;
import java.sql.*;
import org.apache.poi.xwpf.extractor.XWPFWordExtractor;
import org.apache.poi.xwpf.usermodel.*;
import java.util.List;

public final class profiles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"StyleSheet\" href=\"css/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"w3-animate-zoom\" style=\"background:gray\";>\r\n");
      out.write("<!-- Navigation bar -->\r\n");
      out.write("<div class=\"w3-bar w3-bar w3-light-grey w3-card-2\" style=\"width:100%;\">\r\n");
      out.write("<a href=\"#\" class=\"w3-bar-item w3-button w3-red w3-mobile w3-padding-large\"><i class=\"fa fa-bed w3-margin-right\"></i>Here the Logo</a>\r\n");
      out.write("  <!-- a href=\"ViewProfile.jsp\" class=\"w3-bar-item w3-button w3-padding-large\">View Profile</a> \r\n");
      out.write("   <a href=\"userhome.jsp\" class=\"w3-bar-item w3-button w3-padding-large\">Back to home</a>\r\n");
      out.write("    <a href=\"Searching?skilltype=Exclude&&txt_skills=''&&admin=no\" class=\"w3-bar-item w3-button w3-padding-large\">Search profiles</a>  -->\r\n");
      out.write("\r\n");
      out.write("  <a href=\"Index.html\" class=\"w3-bar-item w3-button w3-red w3-right w3-mobile w3-padding-large\">logout</a>\r\n");
      out.write("<a href=\"#\" class=\"w3-bar-item w3-button w3-right w3-padding-large\">Settings</a> \r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Navigation bar --> \r\n");
      out.write("\r\n");


final int BUFFER_SIZE = 4096;  
String url = "jdbc:mysql://localhost:3306/vtjdm01_2019";
   String user = "root";
   String password = "root";
   String filePath = "temp.docx";
	File f=new File(filePath);
   try {
   	Class.forName("com.mysql.jdbc.Driver");
       Connection conn = DriverManager.getConnection(url, user, password);
       String mail=request.getParameter("name");
       System.out.println("User :"+mail);
       String sql = "select * from trails where mail='"+session.getAttribute("mail")+"'";
       String name = "";
       String mobile = "";
       String mail1 = "";
       PreparedStatement statement = conn.prepareStatement(sql);
      // statement.setInt(1, 1);
       ResultSet result = statement.executeQuery();

      	
      out.write("\r\n");
      out.write("     \t<div id=hrpro class=\"w3-card-4 \" Style=\"width:300px;height:800px;left:20px;top:100px;position: fixed;  \">");
 
       if(result.next())
       {
    	   name = result.getString(2) + " " + result.getString(3);
    	   
		
      out.write("\r\n");
      out.write("     \t<img src=\"img/user.png\" id=hrpic width=100% height=300px alt=hrpic /><br><br><br> \r\n");
      out.write("     \tCOMPANY_NAME:");
      out.print(result.getString(1) );
      out.write("<br><br>\r\n");
      out.write("     \tNAME:");
      out.print(result.getString(2) );
      out.write(' ');
      out.print(result.getString(3) );
      out.write("<br><br>\r\n");
      out.write("     \tMail Id:");
      out.print(result.getString(4) );
      out.write("<br><br>\r\n");
      out.write("     \tMobile:");
      out.print(result.getString(3) );
      out.write("<br><br>\r\n");
      out.write("     \t<br><br>\r\n");
      out.write("     \t");

       }
      out.write("\r\n");
      out.write("       <a class=\"w3-btn w3-teal\" Style=\"width: 100%;\"  href=\"#\" >Send to Admin</a><br><br>\r\n");
      out.write("       <a class=\"w3-btn w3-teal\" Style=\"width: 100%;\" >Settings</a>\r\n");
      out.write("     \t</div> \r\n");
      out.write("     \t\r\n");
      out.write("    <div class=\"w3-cotainer\" Style=\"left:350px;top: 100px;position: absolute;width: 1000px;\" >\r\n");
      out.write("      ");
 
      sql = "select * from trails where mail='"+mail+"'";
      PreparedStatement ps=conn.prepareStatement(sql);
      result = ps.executeQuery();
       while(result.next()) {
    	 
      out.write("\r\n");
      out.write("    \t\r\n");
      out.write("\t\t<div class=\"w3-card-4\" style=\"height:300px\" >\r\n");
      out.write("\t\t\t<div id=prohead style=\"height: 50px; width: 100%; background-color: #33adff;\"><h2>Candidate Profile</h2></div>\r\n");
      out.write("\t\t\t<div id=prodiv>\r\n");
      out.write("\t\t\t\t<div class=\"w3-container\"style=\"top: 50px; left: 0px; position: absolute; padding-left: 126px; width: 100%;\" id=tab1>\r\n");
      out.write("\t\t\t\t\t<img src=\"img/user.png\" Style=\"height: 250px; width: 230px; top: 10px; left: 0px; position: absolute;\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t <form action=\"Send_to_admin.jsp\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: inline-block;left: 210px;position: relative; \">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"w3-table\" style=\"left: 10px ;position: relative;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Company_Name</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>");
      out.print(result.getString(1));
      out.write(" </label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Name</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>");
      out.print(result.getString(2));
      out.write(" </label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>KeySkills</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>");
      out.print(result.getString(15));
      out.write("</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Email_Id</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>");
      out.print(result.getString(4));
      out.write("</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Company</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>");
      out.print(result.getString(16));
      out.write("</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>MobileNumber</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>");
      out.print(result.getString(3));
      out.write("</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Nationality</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label>Indian</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><a href=\"Send_to_admin.jsp?mail=");
      out.print( result.getString(4) );
      out.write("&&name=");
      out.print( result.getString(2) );
      out.write("&&mobile=");
      out.print( result.getString(3));
      out.write("\" style=\"\">Send to admin</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
	
           Blob blob = result.getBlob(19);
           InputStream inputStream = blob.getBinaryStream(); 
           OutputStream outputStream = new FileOutputStream( new File(filePath));
           int bytesRead = -1;
           byte[] buffer = new byte[BUFFER_SIZE];
           while ((bytesRead = inputStream.read(buffer)) != -1) {
        	   
               outputStream.write(buffer, 0, bytesRead);
           }
         
           XWPFDocument docx = new XWPFDocument(new FileInputStream(filePath));
           //using XWPFWordExtractor Class
           
      out.write("\r\n");
      out.write("           <form action=\"Download\" method=\"post\">\r\n");
      out.write("           <input type=\"hidden\" name=sub value=\"");
      out.print(result.getString(4) );
      out.write("\">\r\n");
      out.write("           <div id=resumehead style=\"height:50px;width:100%;background-color:#33adff;top:50px;position:relative;\"><h3>Candidate Resume<button type=\"Submit\" class=\"w3-button\" style=\"float: right;\" ><span class=\"fa fa-download w3-xxlarge\"></span></button></h3></div>\r\n");
      out.write("           </form>\r\n");
      out.write("\t\t\t<div id=resume class=\"w3-card-4\" style=\"color:black;width:100%;height:550px;overflow: auto;\">\r\n");
      out.write("           ");
 
           XWPFWordExtractor we = new XWPFWordExtractor(docx);
           List<IBodyElement> list=docx.getBodyElements();
           int i=0,j=0;
           for(IBodyElement body:list)
           {	
           	if(body.getElementType().toString().equals("TABLE"))
           	{
           		XWPFTable ib=body.getBody().getTableArray(i);
       				i++;
	                
      out.write("\r\n");
      out.write("\t                \t<table>");

	                	List<XWPFTableRow> trow=ib.getRows();
	                			for(XWPFTableRow tr:trow)
	                			{
	                				List<XWPFTableCell> tcol=tr.getTableCells(); 
      out.write("\r\n");
      out.write("\t                \t\t\t\t<tr>");
 
	                				for(XWPFTableCell tc:tcol)
	                				{
      out.write("\r\n");
      out.write("\t                \t\t\t\t<td>");
      out.print(tc.getText());
      out.write("</td>");
 
	                				}
	                				
      out.write("</tr>");

	                			}
	                			 
      out.write("</table>");

	                
	                	
	                
           	}
           	else{
      out.write("\r\n");
      out.write("           \t<p>");
      out.print(body.getBody().getParagraphArray(j).getParagraphText() );
      out.write("</p>\r\n");
      out.write("         \r\n");
      out.write("           ");
 
           j++;
           }
           
           	}
           
           inputStream.close();
           outputStream.close();
          System.out.println(f.getAbsolutePath());
         
       }
       conn.close();
   } catch (SQLException ex) {
       ex.printStackTrace();
   } catch (IOException ex) {
       ex.printStackTrace();
   } catch (ClassNotFoundException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	} 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
