/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-11-24 05:46:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.sql.*;
import org.apache.poi.xwpf.extractor.XWPFWordExtractor;
import org.apache.poi.xwpf.usermodel.*;
import java.util.ArrayList;

public final class Robot_005fhome1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Short list</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"StyleSheet\" href=\"css/w3.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function btn1()\r\n");
      out.write("{\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"search\").style.display = \"block\";\r\n");
      out.write("\tdocument.getElementById(\"loc_search\").style.display = \"none\";\r\n");
      out.write("\tdocument.getElementById(\"ind_search\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("function btn2()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"search\").style.display = \"none\";\r\n");
      out.write("\tdocument.getElementById(\"loc_search\").style.display = \"none\";\r\n");
      out.write("\tdocument.getElementById(\"ind_search\").style.display = \"block\";\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function btn3()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"search\").style.display = \"none\";\r\n");
      out.write("\tdocument.getElementById(\"loc_search\").style.display = \"block\";\r\n");
      out.write("\tdocument.getElementById(\"ind_search\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("function clear()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"search\").style.display = \"none\";\r\n");
      out.write("\tdocument.getElementById(\"loc_search\").style.display = \"none\";\r\n");
      out.write("\tdocument.getElementById(\"ind_search\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"clear()\" class=\"w3-animate-zoom\" style=\"background:gray\";>\r\n");
      out.write("\r\n");
      out.write("\r\n");

final int BUFFER_SIZE = 4096;  
String url = "jdbc:mysql://localhost:3306/vtjdm01_2019";
   String user = "root";
   ArrayList<String> list;
   String password = "root";
   String filePath = "temp.docx";
   HttpSession session1=request.getSession(false);
   Object uid=session1.getAttribute("UI");
   try{
	list=(ArrayList)session1.getAttribute("list");
	for(String s:list)
		{
			System.out.println(s);
		}
   }catch(NullPointerException n)
   {
	   list=null;
   }
  		
   try {
   	Class.forName("com.mysql.jdbc.Driver");
       Connection conn = DriverManager.getConnection(url, user, password);
       String mail="";
       String sql = "select * from trails";
      
       PreparedStatement statement = conn.prepareStatement(sql);
      // statement.setInt(1, 1);
       ResultSet result = statement.executeQuery();

      
      out.write("\r\n");
      out.write("      <!-- Navigation bar -->\r\n");
      out.write("<div class=\"w3-bar w3-bar w3-light-grey w3-card-2\" style=\"width:100%;\">\r\n");
      out.write("<a href=\"#\" class=\"w3-bar-item w3-button w3-red w3-mobile w3-padding-large\"><i class=\"fa fa-bed w3-margin-right\"></i>Here the Logo</a>\r\n");
      out.write("  <!-- <a href=\"ViewProfile.jsp\" class=\"w3-bar-item w3-button w3-padding-large\">View Profile</a> \r\n");
      out.write("<a href=\"userhome.jsp\" class=\"w3-bar-item w3-button w3-padding-large\">Back to home</a>\r\n");
      out.write("    <a href=\"Searching?skilltype=Exclude&&txt_skills=''&&admin=no\" class=\"w3-bar-item w3-button w3-padding-large\">Search profiles</a>  -->\r\n");
      out.write("  <a href=\"Index.html\" class=\"w3-bar-item w3-button w3-red w3-right w3-mobile w3-padding-large\">logout</a>\r\n");
      out.write("<a href=\"#\" class=\"w3-bar-item w3-button w3-right w3-padding-large\">Settings</a> \r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Navigation bar --> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Filtering area -->\r\n");
      out.write("<div id=reg class=\" \" >\r\n");
      out.write("<div class=\"w3-card-4\" style=\"left:350px;position: absolute;width:1000px;height:250px; \">\r\n");
      out.write("  <div class=\"w3-container w3-teal\" style=\"\"> \r\n");
      out.write("        <h2>Filter resumes here</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("<div style=position:relative; class=\"w3-center\">\r\n");
      out.write("<button class=\" w3-btn w3-teal \" Style=\"width:250px;\" id=bb1 onclick=\"btn1()\" value=\"\">Skills <span class=\"glyphicon glyphicon-chevron-down\"></span></button>\r\n");
      out.write("<!-- <button class=\" w3-btn w3-teal \" Style=\"width:250px;\" id=bb2 onclick=\"btn3()\" value=\"\">Experience <span class=\"glyphicon glyphicon-chevron-down\"></span></button> -->\r\n");
      out.write("<!-- <button class=\" w3-btn w3-teal \" Style=\"width:250px;\" id=bb3 onclick=\"btn2()\" value=\"\" disabled=\"disabled\">Function <span class=\"glyphicon glyphicon-chevron-down\"></span></button> -->\r\n");
      out.write("</div><br>\r\n");
      out.write("<div id=search class=\"w3-center\">\r\n");
      out.write("<form action=\"Searching\" method=\"get\">\r\n");
      out.write("<input type=\"hidden\" value=\"no\" name=admin>\r\n");
      out.write("<table class=\"w3-table\"><tr>\r\n");
      out.write("\r\n");
      out.write("<td><input class=\" \" Style=\"width:350px;height: 50px;\" type=text name=txt_skills id=skills></td>\r\n");
      out.write("<td><input class=\"w3-radio\" type=radio name=skilltype value=Any><strong> Any</strong></td>\r\n");
      out.write("<td><input class=\"w3-radio\" type=radio name=skilltype value=All><strong> All</strong></td>\r\n");
      out.write("<td><input class=\"w3-radio\" type=radio name=skilltype value=Exclude><strong> Exclude</strong></td>\r\n");
      out.write("<td><input class=\"w3-btn w3-teal\" Style=\"width:250px;\" type=Submit value=search></td></tr></table>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<form id=myform action=NoticeCal method=post>\r\n");
      out.write("<div id=loc_search>\r\n");
      out.write("<table class=\"w3-table\"><tr><td><strong>Min Notice period</strong><select name=note_min onchange=\"change()\" class=\"w3-select w3-teal\">\r\n");
      out.write("<option value=0>immediate</option>\r\n");
      out.write("<option value=15>15 days</option>\r\n");
      out.write("<option value=30>30 days</option>\r\n");
      out.write("<option value=45>45 days</option>\r\n");
      out.write("<option value=60>2 months</option>\r\n");
      out.write("<option value=90>3 months</option>\r\n");
      out.write("<option value=180>6 months</option>\r\n");
      out.write("</select></td><td><strong>Max Notice period</strong><select name=note_max onchange=\"change()\" class=\"w3-select w3-teal\">\r\n");
      out.write("<option value=0>immediate</option>\r\n");
      out.write("<option value=15>15 days</option>\r\n");
      out.write("<option value=30>30 days</option>\r\n");
      out.write("<option value=45>45 days</option>\r\n");
      out.write("<option value=60>2 months</option>\r\n");
      out.write("<option value=90>3 months</option>\r\n");
      out.write("<option value=180>6 months</option>\r\n");
      out.write("</select></td><td><strong>Min Experience</strong><select name=ex_min onchange=\"change()\" class=\"w3-select w3-teal\">\r\n");
      out.write("<option value=0>fresher</option>\r\n");
      out.write("<option value=6>6 months</option>\r\n");
      out.write("<option value=12>1 year</option>\r\n");
      out.write("<option value=24>2 years</option>\r\n");
      out.write("<option value=36>3 years</option>\r\n");
      out.write("<option value=48>4 years</option>\r\n");
      out.write("<option value=60>5 years</option>\r\n");
      out.write("</select></td><td><strong>Max Experience</strong><select name=ex_max onchange=\"change()\" class=\"w3-select w3-teal\">\r\n");
      out.write("<option value=0>fresher</option>\r\n");
      out.write("<option value=6>6 months</option>\r\n");
      out.write("<option value=12>1 year</option>\r\n");
      out.write("<option value=24>2 years</option>\r\n");
      out.write("<option value=36>3 years</option>\r\n");
      out.write("<option value=48>4 years</option>\r\n");
      out.write("<option value=60>5 years</option>\r\n");
      out.write("</select></td><td><input type=submit value=search class=\"w3-btn w3-teal\" Style=\"margin-top: 22px;\"></td></tr></table>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("<!--END Filtering area -->\r\n");
      out.write("<div id=ind_search>\r\n");
      out.write("<table class=\"w3-table\"><tr><td><strong>location</strong><select class=\"w3-select w3-teal\"><option>location</option></select></td>\r\n");
      out.write("<td><strong>industry</strong><select class=\"w3-select w3-teal\"><option>industry</option></select></td>\r\n");
      out.write("<td><strong>function</strong><select class=\"w3-select w3-teal\"><option>Function</option></select></td>\r\n");
      out.write("<td><input class=\"w3-btn w3-teal\" type=submit value=search Style=\"margin-top: 22px;\"></td></tr></table>\r\n");
      out.write("</div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END Filtering area  -->\r\n");
      out.write("          <div style=\"top: 300px;left: 350px;position: absolute;\">\r\n");
      out.write("     \t");
 
       while(result.next()) {
    	   for(String l:list)
			{
				if(result.getString(2).equalsIgnoreCase(l))
				{
				
				
    	 
      out.write(" <div class=\"w3-card-4 \" style=\"left:0px;top:10px;position: relative;width:1000px;height:400px;\">\r\n");
      out.write("    \t <div id=prohead style=height:50px;width:100%;background-color:#33adff;><h2 class=\"w3-text-white\">");
      out.print(result.getString(1) );
      out.write(' ');
      out.print(result.getString(3) );
      out.write(" Profile</h2></div>\r\n");
      out.write("\t\t\t<div id=prodiv>\r\n");
      out.write("\t\t\t<table style=top:0px;left:0px;position:relative;padding-left:126px;width:100%; id=tab1>\r\n");
      out.write("\t\t\t<tr><td width=\"200px\">\r\n");
      out.write("\t\t<img src=\"img/user.png\" Style=height:270px;width:230px;top:0px;left:0px;position:absolute;></td>\r\n");
      out.write("<td> <table class=\"w3-table\">\r\n");
      out.write(" \t\t\t<tr><td>Company_Name</td><td><label>");
      out.print(result.getString(1) );
      out.write("</label></td></tr>\r\n");
      out.write("    \t   <tr><td>Name</td><td><label>");
      out.print(result.getString(2) );
      out.write("</label></td></tr>\r\n");
      out.write("    \t   <tr><td>mobile</td><td><label>");
      out.print(result.getString(3) );
      out.write("</label></td></tr>\r\n");
      out.write("    \t   <tr><td>mail</td><td><label>");
      out.print(result.getString(4) );
      out.write("</label></td></tr>\r\n");
      out.write("    \t   <tr><td>address</td><td><label>");
      out.print(result.getString(5) );
      out.write("</label></td></tr>\r\n");
      out.write("    \t   ");
      out.write("</tr>\r\n");
      out.write("    \t   \r\n");
      out.write("    \t   \r\n");
      out.write("    \t    ");
      out.write("\r\n");
      out.write("    \t    </table></td></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div id=profoot class=\"w3-panel\" style=\"height:50px;width:100%;bottom:10px;position:absolute ;\">\r\n");
      out.write("\t\t\t<form action=\"profiles.jsp\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=");
      out.print(result.getString(4));
      out.write(" name=name>\r\n");
      out.write("\t\t\t<h3><input type=Submit class=\"w3-btn w3-teal\" value=\"view full profile\"></a></h3>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
 }
			}}
        conn.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
    } catch (IOException ex) {
        ex.printStackTrace();
    } catch (Exception e) {
 		// TODO Auto-generated catch block
 		e.printStackTrace();
 	} 
   
     	
      out.write("\r\n");
      out.write("     \t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
